{
 "title": "DORA Metrics Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Deployment Frequency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(deployments_total[1d])" }
   ]
  },
  {
   "title": "Lead Time for Changes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "avg(lead_time_seconds)" }
   ]
  },
  {
   "title": "Mean Time to Recovery (MTTR)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "avg(mttr_seconds)" }
   ]
  },
  {
   "title": "Change Failure Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(failed_deployments_total) / sum(deployments_total)"
    }
   ]
  }
 ]
}