openapi: 3.0.0
info:
  title: Cart Management API
  version: 1.0.0
  description: REST API service for managing shopping carts and cart items, enabling creation, modification and retrieval of cart data.

paths:
  /carts:
    post:
      summary: Create Cart
      operationId: createCart
      description: Creates a new empty shopping cart for a customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCartRequest'
      responses:
        '201':
          description: Cart created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCartResponse'
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /carts/{cartId}/items:
    post:
      summary: Add Item to Cart
      operationId: addItem
      description: Adds a product item to an existing shopping cart
      parameters:
        - name: cartId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddItemRequest'
      responses:
        '200':
          description: Item added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddItemResponse'
        '400':
          description: Bad request
        '404':
          description: Cart not found
        '500':
          description: Internal server error

  /carts/{cartId}:
    get:
      summary: Get Cart Details
      operationId: getCart
      description: Retrieves the current state of a shopping cart
      parameters:
        - name: cartId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful retrieval of cart details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCartResponse'
        '404':
          description: Cart not found
        '500':
          description: Internal server error

components:
  schemas:
    CreateCartRequest:
      type: object
      properties:
        customerId:
          type: string
      required:
        - customerId

    CreateCartResponse:
      type: object
      properties:
        cartId:
          type: string
        createdAt:
          type: string
          format: date-time
      required:
        - cartId
        - createdAt

    AddItemRequest:
      type: object
      properties:
        productId:
          type: string
        quantity:
          type: integer
          minimum: 1
      required:
        - productId
        - quantity

    AddItemResponse:
      type: object
      properties:
        cartId:
          type: string
        items:
          type: array
          items:
            type: object
            properties:
              productId:
                type: string
              quantity:
                type: integer
      required:
        - cartId
        - items

    GetCartResponse:
      type: object
      properties:
        cartId:
          type: string
        customerId:
          type: string
        items:
          type: array
          items:
            type: object
            properties:
              productId:
                type: string
              quantity:
                type: integer
        totalAmount:
          type: number
      required:
        - cartId
        - customerId
        - items
        - totalAmount