openapi: 3.0.0
info:
  title: Inventory Service API
  version: 1.0.0
  description: Manages inventories, items, product variants, and locations within the system, providing comprehensive inventory control and tracking capabilities.

paths:
  /inventory:
    get:
      summary: Get Inventory Level
      operationId: getInventoryLevel
      description: Retrieves current inventory level for a specific product variant at a given location
      parameters:
        - name: variantId
          in: query
          required: true
          schema:
            type: string
        - name: locationId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful retrieval of inventory level
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InventoryLevelResponse'
        '400':
          description: Bad request
        '404':
          description: Variant or location not found
        '500':
          description: Internal server error

    post:
      summary: Adjust Inventory
      operationId: adjustInventory
      description: Updates inventory quantity for a specific product variant at a location
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdjustInventoryRequest'
      responses:
        '200':
          description: Inventory adjusted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdjustInventoryResponse'
        '400':
          description: Bad request
        '404':
          description: Variant or location not found
        '500':
          description: Internal server error

  /locations:
    post:
      summary: Create Location
      operationId: createLocation
      description: Creates a new inventory location in the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateLocationRequest'
      responses:
        '201':
          description: Location created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateLocationResponse'
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /variants:
    post:
      summary: Add Product Variant
      operationId: addProductVariant
      description: Adds a new product variant to inventory tracking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddProductVariantRequest'
      responses:
        '201':
          description: Product variant added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddProductVariantResponse'
        '400':
          description: Bad request
        '500':
          description: Internal server error

components:
  schemas:
    InventoryLevelResponse:
      type: object
      properties:
        quantity:
          type: number
        availableQuantity:
          type: number
        reservedQuantity:
          type: number

    AdjustInventoryRequest:
      type: object
      properties:
        variantId:
          type: string
        locationId:
          type: string
        adjustment:
          type: number
        reason:
          type: string
      required:
        - variantId
        - locationId
        - adjustment

    AdjustInventoryResponse:
      type: object
      properties:
        success:
          type: boolean
        newQuantity:
          type: number

    CreateLocationRequest:
      type: object
      properties:
        name:
          type: string
        address:
          type: object
        type:
          type: string
      required:
        - name

    CreateLocationResponse:
      type: object
      properties:
        locationId:
          type: string
        name:
          type: string
        status:
          type: string

    AddProductVariantRequest:
      type: object
      properties:
        productId:
          type: string
        sku:
          type: string
        attributes:
          type: object
      required:
        - productId
        - sku

    AddProductVariantResponse:
      type: object
      properties:
        variantId:
          type: string
        sku:
          type: string
        status:
          type: string